// <auto-generated />
using MarcasAutos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarcasAutos.Migrations
{
    [DbContext(typeof(MarcasAutosDbContext))]
    partial class MarcaAutosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarcasAutos.Entities.MarcaAuto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Creador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MarcasAutos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creador = "August Horch",
                            Nombre = "Audi"
                        },
                        new
                        {
                            Id = 2,
                            Creador = "",
                            Nombre = "Porsche"
                        },
                        new
                        {
                            Id = 3,
                            Creador = "Karl Benz",
                            Nombre = "Mercedes Benz"
                        },
                        new
                        {
                            Id = 4,
                            Creador = "Enzo Ferrari",
                            Nombre = "Ferrari"
                        },
                        new
                        {
                            Id = 5,
                            Creador = "",
                            Nombre = "Subaru"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
